language: node_js

addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - g++-4.8

services:
        - docker

before_install:
    - export CXX="g++-4.8"
    - npm install juttle@0.2.x

node_js:
    - '4.2'
    - '5.0'

before_script:
    - docker run -d -p 4444:4444 --name selenium-hub selenium/hub
    - docker run -d --link selenium-hub:hub --name selenium-node-chrome selenium/node-chrome

script:
    - gulp lint
    - OUTRIGGER_HOST=172.17.42.1 SELENIUM_REMOTE_URL='http://localhost:4444/wd/hub' gulp test-coverage --app
