elasticsearch:
  image: elasticsearch:2.1.1

logstash:
  image: logstash:2.1.1
  links:
    -  elasticsearch
  volumes:
    - ${PWD}/news_data.zip:/incoming/news_data.zip
    - ${PWD}/logstash.conf:/config/logstash.conf
  command: bash -c 'unzip -c -q /incoming/news_data.zip | logstash -f /config/logstash.conf -w 4'

outrigger:
  image: juttle/outrigger:latest
  volumes:
    - ${PWD}/juttles:/opt/outrigger/juttles
    - ${PWD}/juttle-config.json:/opt/outrigger/.juttle-config.json
  command: outriggerd --root /opt/outrigger/juttles
  ports:
    - "8080:8080"
  links:
    - elasticsearch

